/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "seguimiento.buscar": [],
    "design-system": [],
    "dashboard": [],
    "reportes.index": [],
    "reportes.preview": [],
    "reportes.exportar": [],
    "denuncias.bandeja": [],
    "denuncias.registrar": [],
    "denuncias.store": [],
    "denuncias.admitir": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.rechazar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.iniciar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.asignar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.traspasar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.reabrir": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.saltar-fase": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.informe.guardar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.informe.editar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.informe.eliminar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.cierre.guardar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.cierre.editar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.cierre.eliminar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.archivar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.carga-tecnicos": [],
    "denuncias.delegar-evaluacion": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.reasumir-evaluacion": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.evaluaciones.devolver": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.ampliar-plazo": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.editar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.eliminar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.conciliar-fechas": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.consultar": [],
    "denuncias.archivos.listar": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.archivos.subir": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.archivos.eliminar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.solicitudes.store": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.solicitudes.responder": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.solicitudes.ampliar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.solicitudes.cancelar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.solicitudes.editar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.solicitudes.eliminar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.store": [
        {
            "name": "ticket",
            "required": true
        }
    ],
    "denuncias.descargos.notificar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.responder": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.ampliar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.cancelar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.editar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.descargos.eliminar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "denuncias.mis-casos": [],
    "denuncias.mi-resumen": [],
    "denuncias.evaluaciones": [],
    "admin.catalogos": [],
    "notificaciones.index": [],
    "notificaciones.marcar-leida": [
        {
            "name": "id",
            "required": true
        }
    ],
    "notificaciones.marcar-todas": [],
    "admin.catalogos.store": [
        {
            "name": "tipo",
            "required": true
        }
    ],
    "admin.catalogos.update": [
        {
            "name": "tipo",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.catalogos.destroy": [
        {
            "name": "tipo",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.catalogos.reactivar": [
        {
            "name": "tipo",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "notifications.stream": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "login": [],
    "password.update": [],
    "logout": []
}
}
export {};
